name: snack_scroll
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_custom_carousel: ^0.1.0+1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0





flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/svg/
  

  
   
  
  
  
  
  
  
  
  
